# Generated by Django 5.1.6 on 2025-02-19 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('name_use', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('birth_date', models.DateField(max_length=50)),
                ('height_feet', models.IntegerField()),
                ('height_inches', models.IntegerField(null=True)),
                ('weight', models.IntegerField()),
                ('throws', models.CharField(max_length=10)),
                ('bats', models.CharField(max_length=10)),
                ('primary_position', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PitchingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('league', models.CharField(max_length=10)),
                ('org_abbreviation', models.CharField(max_length=10)),
                ('games', models.IntegerField()),
                ('games_started', models.IntegerField()),
                ('complete_games', models.IntegerField()),
                ('games_finished', models.IntegerField()),
                ('innings_pitched', models.FloatField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('saves', models.IntegerField()),
                ('total_batters_faced', models.IntegerField()),
                ('at_bats', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('doubles', models.IntegerField()),
                ('triples', models.IntegerField()),
                ('home_runs', models.IntegerField()),
                ('bases_on_balls', models.IntegerField()),
                ('strikeouts', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitching_stats', to='app.player')),
            ],
        ),
        migrations.CreateModel(
            name='BattingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('league', models.CharField(max_length=10)),
                ('org_abbreviation', models.CharField(max_length=10)),
                ('plate_appearances', models.IntegerField()),
                ('at_bats', models.IntegerField()),
                ('games', models.IntegerField()),
                ('games_started', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('doubles', models.IntegerField()),
                ('triples', models.IntegerField()),
                ('home_runs', models.IntegerField()),
                ('bases_on_balls', models.IntegerField()),
                ('strikeouts', models.IntegerField()),
                ('sacrifices', models.IntegerField()),
                ('sacrifice_flies', models.IntegerField()),
                ('stolen_bases', models.IntegerField()),
                ('caught_stealing', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_stats', to='app.player')),
            ],
        ),
    ]
