# Generated by Django 5.1.6 on 2025-02-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battingstats',
            name='league',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pitchingstats',
            name='league',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.CharField(max_length=50),
        ),
    ]
