# Generated by Django 5.1.6 on 2025-02-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_battingstats_league_alter_pitchingstats_league_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battingstats',
            name='league',
            field=models.CharField(default='Not Available', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pitchingstats',
            name='league',
            field=models.CharField(default='Not Available', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='primary_position',
            field=models.CharField(default='Not Available', max_length=25, null=True),
        ),
    ]
