# Generated by Django 5.1.6 on 2025-02-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_battingstats_league_alter_pitchingstats_league_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height_inches',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
